export const GET_CRYPTO_API = 'GET_CRYPTOS';
export const LOADING_CRYPTO_API = 'LOADING_CRYPTO_API';
export const GET_CRYPTO_API_ERROR = 'GET_CRYPTO_API_ERROR';

export const GET_CRYPTO_NEWS = 'GET_CRYPTO_NEWS';
export const LOADING_CRYPTO_NEWS = 'LOADING_CRYPTO_NEWS';
export const LOADING_CRYPTO_NEWS_ERROR = 'LOADING_CRYPTO_NEWS_ERROR';
